### ISSUE TITLE
config --shell adds errant \ characters

### ISSUE THREAD

**Issue by csuhta** [heroku/heroku#1481] opened 2015-04-01 22:06 UTC
CLI version `3.30.3`. 

We have some config vars with `+` characters in them. `heroku config` returns the correct value of the variables to us, however `heroku config --shell` is adding extra `\` characters to the front of `+` signs when it reports the values.

```
$ heroku version
heroku-toolbelt/3.30.3 (x86_64-darwin10.8.0) ruby/1.9.3
=== Installed Plugins
heroku-repo

$ heroku apps:create
Creating blueberry-crisp-4373... done, stack is cedar-14
https://blueberry-crisp-4373.herokuapp.com/ | https://git.heroku.com/blueberry-crisp-4373.git

$ heroku config:set TEST_VAR=+tQ405404230 --app blueberry-crisp-4373
Setting config vars and restarting blueberry-crisp-4373... done, v3
TEST_VAR: +tQ405404230

$ heroku config --app blueberry-crisp-4373
=== blueberry-crisp-4373 Config Vars
TEST_VAR: +tQ405404230

$ heroku config --shell --app blueberry-crisp-4373
TEST_VAR=\+tQ405404230
```

**Comment by dickeyxxx** [comment] 2015-04-01 22:08
that is expected behavior since it escapes them with shellescape http://ruby-doc.org/stdlib-1.9.3/libdoc/shellwords/rdoc/Shellwords.html#method-c-shellescape

**Comment by csuhta** [comment] 2015-04-01 22:12
That's rather surprising, at least to me. What is the expect use-case for `heroku config --shell` with these escape markers? Is it only for scripting?

I have been using `heroku config --shell` as a convenient way to print config vars formatted for copy-pasting into a foreman `.env` file. But the way they are printed currently is incorrect for this workflow.

**Comment by dickeyxxx** [comment] 2015-04-01 22:17
It's designed to be used as Unix shell code, so yeah, scripting. I'm a little surprised the .env file doesn't work in this case. @ddollar does the .env file work with escaped shell characters?

**Comment by csuhta** [comment] 2015-04-01 22:22
They seem to be interpreted literally:

```
$ cat .env 
TEST_VAR=\+4050

$ foreman run irb

>> puts ENV.fetch("TEST_VAR")
\+4050
=> nil

>> ENV.fetch("TEST_VAR").chars
=> ["\\", "+", "4", "0", "5", "0"]
```

**Comment by dickeyxxx** [comment] 2015-04-29 17:41
@csuhta I think I've resolved this issue for you but in a different way. These shouldn't have been escaped if you were creating these files by doing something like `heroku config -s >> .env`. This is resolved in #1518

**Comment by csuhta** [comment] 2015-05-03 02:39
I just tried with 3.33.0 and it works great for this. Thanks!

**Closed** 2015-05-04 19:17 UTC

**Comment by lincolnq** [comment] 2015-06-25 14:00
I'm not satisfied with this solution at all :( -- if you do it this way, there's no way to get the escaped versions programmatically, which kind of defeats the purpose of having them unless you are just going to copy/paste it from your terminal. 

Furthermore, the unescaped output often contains characters (such as \n) which wreck .env files so you can't safely use the unescaped one either.

**Comment by dickeyxxx** [comment] 2015-06-29 22:40
can I ask why you want to pipe the escaped version? You make a good point about `\n`. I just noticed that is kind of weird for most of the config commands.
