### ISSUE TITLE
NaN when running heroku pg:backups info

### ISSUE THREAD

**Issue by diwu1989** [heroku/heroku#1494] opened 2015-04-09 04:07 UTC
```
Heroku client internal error.
NaN
/usr/local/heroku/lib/heroku/command/pg_backups.rb:258:in `round'
/usr/local/heroku/lib/heroku/command/pg_backups.rb:258:in `backup_status'
/usr/local/heroku/lib/heroku/command/pg_backups.rb:55:in `backups'
/usr/local/heroku/lib/heroku/command.rb:223:in `run'
/usr/local/heroku/lib/heroku/cli.rb:45:in `start'
/usr/local/heroku/bin/heroku:25:in `<main>'
Heroku client internal error.
NaN
/usr/local/heroku/lib/heroku/command/pg_backups.rb:258:in `round'
/usr/local/heroku/lib/heroku/command/pg_backups.rb:258:in `backup_status'
/usr/local/heroku/lib/heroku/command/pg_backups.rb:55:in `backups'
/usr/local/heroku/lib/heroku/command.rb:223:in `run'
/usr/local/heroku/lib/heroku/cli.rb:45:in `start'
/usr/local/heroku/bin/heroku:25:in `<main>'
Heroku client internal error.
NaN
/usr/local/heroku/lib/heroku/command/pg_backups.rb:258:in `round'
/usr/local/heroku/lib/heroku/command/pg_backups.rb:258:in `backup_status'
/usr/local/heroku/lib/heroku/command/pg_backups.rb:55:in `backups'
/usr/local/heroku/lib/heroku/command.rb:223:in `run'
/usr/local/heroku/lib/heroku/cli.rb:45:in `start'
/usr/local/heroku/bin/heroku:25:in `<main>'
```

**Comment by diwu1989** [comment] 2015-04-09 04:10
also seeing
```
Heroku client internal error.
comparison of String with nil failed
/usr/local/heroku/lib/heroku/command/pg_backups.rb:339:in `sort_by'
/usr/local/heroku/lib/heroku/command/pg_backups.rb:339:in `restore_backup'
/usr/local/heroku/lib/heroku/command/pg_backups.rb:57:in `backups'
/usr/local/heroku/lib/heroku/command.rb:223:in `run'
/usr/local/heroku/lib/heroku/cli.rb:45:in `start'
/usr/local/heroku/bin/heroku:25:in `<main>'
```
when running restore

**Comment by uhoh-itsmaciek** [comment] 2015-04-09 17:42
Thanks for reporting this. I've reproduced the first issue you ran into and I'm looking at the second one. I should have a fix shortly.

**Comment by uhoh-itsmaciek** [comment] 2015-04-10 01:28
Closing since #1498 is merged. Let us know if you still have problems.

**Closed by uhoh-itsmaciek** 2015-04-10 01:28 UTC
